### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by robertlong** [iimachines/Maya2glTF#24]
I'm interested in getting work started on macOS support. Does anyone have an idea of what is currently needed to add macOS support. Besides moving everything to CMAKE, are there other dependencies that are Windows specific right now? @donmccurdy mentioned COLLADA2GLTF may not have macOS support yet.

**Comment by Ziriax** [comment]
@robertlong That's amazing! I'm honored 👍 

Currently the `dependencies` folder lists:
```
COLLADA2GLTF
GSL
cpp-linq
```
All of these should be platform independent.

From `COLLADA2GLTF`, I only use the `GLTF` submodule.

I don't use `cpp-linq` that much, so if needed it could be removed by changing a few lines of code (as a C# LINQ fan, I discovered this library too late, otherwise I would have used it  a lot). 

I do use windows-specific code for fatal exception handling, but that is inside a `#ifdef _MSC_VER`.

In general, I wrote this code to be platform independent.

The main concerns are:
- `C++17` 
- `using namespace std::experimental` for `filesystem` and `path` classes

I just pushed a commit that removed some unused `#include` statements, so porting will be easier.

Again, thanks a lot!
Peter

PS: I'm not 100% happy with the current code base, but I will never be ;-) The original plan was to create `MayaXXX` specific classes to convert Maya's dependency graph into something easier to convert to whatever format, and then `ExportableXXX` classes that took care of the actual GLTF export, but when I started implementing skinning and animation,  I wasn't able to keep this up... That's why the architecture is not perfect yet, but it requires a lot of refactoring to get it right, and might not be worth it.

**Comment by Ziriax** [comment]
The `cmake` branch now contains an experimental MacOS version. As soon as this is merged into master, I will close this issue.

**Comment by fire** [comment]
> As soon as this is merged into master, I will close this issue.

**Comment by Ziriax** [comment]
The plugin works on MacOS now, we just need an installer.
