### ISSUE TITLE
Don’t remove 0 weighted bones

### ISSUE THREAD

**Issue by fire** [iimachines/Maya2glTF#91]
https://github.com/WonderMediaProductions/Maya2glTF/blob/40b77bc6d5b2d2e5a477a247cbf8f074a75dcca5/src/MeshSkeleton.cpp#L132

Any bones in skin should be kept on export for compatibility purposes.

**Comment by Ziriax** [comment]
Yes, this optimization could be behind an argument indeed. It is code from old exporters that supported a maximum #weights, and it tries to find the weights with the largest influence.

**Comment by fire** [comment]
Can you name the flag and I can make sure it's plumbed through?

**Comment by Ziriax** [comment]
I think it is best to change the current behaviour so that all bones are kept, unless a flag is specified that this should be optimised away. 

I suggest a `excludeZeroJoints` flag, `ezj` for short? So when passing the flag `-ezj`, the exporter will not include joints with zero weights in the skeleton, otherwise it will.

As for your other joint related issue, I also think the default behaviour should be to keep all joints defined in a mesh in the skeleton, unless optimised away with a flag, e.g. `excludeUnboundJoints`, `euj`. 

Thanks for these great insights and help!

**Comment by fire** [comment]
We worked around this in Godot Engine using a named Skin system that remaps vertex ids to bone names in the skeleton.
