### ISSUE TITLE
Make merger tool not hardcode a path.

### ISSUE THREAD

**Issue by fire** [iimachines/Maya2glTF#98]
```csharp
new ModelClipMerger(@"D:\Nova\export", @"D:\Nova\glTF")
```

The code currently hard codes a path.

I would suggest for the default to search the working directory and output to glTF.

```csharp
new ModelClipMerger(@".", @"./glTF")
```

Then you can add an argument to search for "D:\Nova\export" and another argument for the output directory "D:\Nova\glTF".

**Comment by Ziriax** [comment]
That could very dangerous IMO, and not very artist friendly? It could create and potentially overwrite a lot of files if the user is not aware of this.

It's best to add real (command line arguments)[https://github.com/commandlineparser/commandline], or by default a dialog box asking the user for input and output folders? I was planning to use https://avaloniaui.net for that.

It was never my intention to already release the GLTF merger tool, that's why it was not in master yet ;-)

But it will be an essential tool in our own workflow one day...


I did use it succesfully on our inhouse characters (reasonably complex). But I suspect a bugs.

**Comment by fire** [comment]
I hope to keep Windows, Mac and Linux support regarding ui and cli.

**Comment by Ziriax** [comment]
Yes, the above frameworks I mentioned are fully cross platform

**Comment by fire** [comment]
Closing because there doesn't seem to anyone using this feature. At least we're not using it.
